### ISSUE TITLE
No module named 'PyCRC'

### ISSUE THREAD

**Issue by iadnan1990** [ITI/PyMU#4]
Hi,
I installed the PyMu library using pip install PyMU.

I ran into a problem while running the QUICKSTART guide to Get Config Frame

import pymu.tools as tools
confFrame = tools.startDataCapture(frameId, port, tcpPort)

![image](https://user-images.githubusercontent.com/57323571/107916995-3ed2b400-6f8d-11eb-83e5-6f36e5198a92.png)

Output

runfile('C:/Users/HP/untitled0.py', wdir='C:/Users/HP')
Traceback (most recent call last):

  File "C:\Users\HP\untitled0.py", line 8, in <module>
    import pymu.tools as tools

  File "C:\Users\HP\anaconda3\lib\site-packages\pymu\tools.py", line 7, in <module>
    from .pmuCommandFrame import CommandFrame

  File "C:\Users\HP\anaconda3\lib\site-packages\pymu\pmuCommandFrame.py", line 5, in <module>
    from PyCRC.CRCCCITT import CRCCCITT

ModuleNotFoundError: No module named 'PyCRC'

**Comment by cdrew3** [comment]
Try pip install pythoncrc.  I believe the module name changed and this repo hasn't been updated.

**Comment by iadnan1990** [comment]
Hi, 
Thankyou for the quick response, I had installed pythoncrc and pycrc, still I am facing the same issue. 


![image](https://user-images.githubusercontent.com/57323571/108344004-9f1e5b80-7202-11eb-86e9-7df6e35e6493.png)


Thanks and regards
Adnan Iqbal

**Comment by aaronli7** [comment]
> Hi,
> Thankyou for the quick response, I had installed pythoncrc and pycrc, still I am facing the same issue.
> 
> ![image](https://user-images.githubusercontent.com/57323571/108344004-9f1e5b80-7202-11eb-86e9-7df6e35e6493.png)
> 
> Thanks and regards
> Adnan Iqbal

FYI, what I did to workaround was changing the PYCRC to lowercase:
"from pycrc.CRCCCITT import CRCCCITT"

**Comment by cdrew3** [comment]
Glad that fixed it!  It's been a couple years since I've run this so I'm not sure why that import failed.  I'll try to dig into it this week and let you know if I figure it out.  

Since I know it was working a couple years back I can't guarantee pycrc will work the same as PyCRC.  This would only affect you if you use the CommandFrame class I believe so if you only care about Config/Data frames you probably won't come across this.

**Comment by iadnan1990** [comment]
Thankyou aaronli-uga and cdew3 the issue is fixed.
